<a href="https://colab.research.google.com/github/l3wandowskyy/Pricing-Footballers-Master/blob/main/preditict_value_footballer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Cleaning

In [47]:
import pandas as pd

# Import data
players = pd.read_excel('players_data_set1.xlsx')

# Count rows and columns
players.shape

(7845, 29)

In [48]:
# Count the empty values in each column
players.isnull().sum()

Player ID                    0
Player Name                  0
Nationality                  0
Team Title                   0
Team Position in League      0
League                       0
UEFA league ranking          0
Position                     0
Birth Date                   0
Height                      51
Foot                        63
Games                        0
Time                         0
Goals                        0
Goal Contribution Share      1
xG                           0
Assists                      0
xA                           0
Shots                        0
Key Passes                   0
Yellow Cards                 0
Red Cards                    0
npg                          0
npxG                         0
xGChain                      0
xGBuildup                    0
Season                       0
Value Date                 145
Market Value               145
dtype: int64

In [49]:
# Delete empty values in Market Value and Goal Contribution Share
players = players.dropna(subset=['Market Value', 'Goal Contribution Share'])

In [50]:
# Fill in the blank values in the height and leg columns
players['Height'] = players['Height'].fillna(players['Height'].mean())
most_common_foot = players['Foot'].mode()[0]
players['Foot'] = players['Foot'].fillna(most_common_foot)

# Count the empty values in each column
players.isnull().sum()

Player ID                  0
Player Name                0
Nationality                0
Team Title                 0
Team Position in League    0
League                     0
UEFA league ranking        0
Position                   0
Birth Date                 0
Height                     0
Foot                       0
Games                      0
Time                       0
Goals                      0
Goal Contribution Share    0
xG                         0
Assists                    0
xA                         0
Shots                      0
Key Passes                 0
Yellow Cards               0
Red Cards                  0
npg                        0
npxG                       0
xGChain                    0
xGBuildup                  0
Season                     0
Value Date                 0
Market Value               0
dtype: int64

In [51]:
# Check the data types of each column
players.dtypes

Player ID                    int64
Player Name                 object
Nationality                 object
Team Title                  object
Team Position in League     object
League                      object
UEFA league ranking          int64
Position                    object
Birth Date                  object
Height                     float64
Foot                        object
Games                        int64
Time                         int64
Goals                        int64
Goal Contribution Share    float64
xG                         float64
Assists                      int64
xA                         float64
Shots                        int64
Key Passes                   int64
Yellow Cards                 int64
Red Cards                    int64
npg                          int64
npxG                       float64
xGChain                    float64
xGBuildup                  float64
Season                      object
Value Date                  object
Market Value               float64
dtype: object

In [52]:
# Change the data type for categorical columns
players["Nationality"] = players["Nationality"].astype("category")
players["Team Title"] = players["Team Title"].astype("category")
players["League"] = players["League"].astype("category")
players["Position"] = players["Position"].astype("category")
players["Foot"] = players["Foot"].astype("category")
players["Season"] = players["Season"].astype("category")

# Convert date columns to datetime format (dd.mm.yyyy)
players["Birth Date"] = pd.to_datetime(players["Birth Date"], format="%d.%m.%Y", errors="coerce")
players["Value Date"] = pd.to_datetime(players["Value Date"], errors="coerce")

# Extract numerical team position from string and convert to Int64
players["Team Position in League"] = players["Team Position in League"].str.extract("(\d+)").astype("Int64")

# Convert height column to Int64
players.loc[:, "Height"] = players["Height"].apply(lambda x: int(x) if pd.notna(x) else None).astype("Int64")

In [53]:
# Show duplicates
players[players.duplicated()]

Empty DataFrame
Columns: [Player ID, Player Name, Nationality, Team Title, Team Position in League, League, UEFA league ranking, Position, Birth Date, Height, Foot, Games, Time, Goals, Goal Contribution Share, xG, Assists, xA, Shots, Key Passes, Yellow Cards, Red Cards, npg, npxG, xGChain, xGBuildup, Season, Value Date, Market Value]
Index: []

[0 rows x 29 columns]

In [54]:
# Rename columns
rename_dict = {
    "Games": "Matches (Season)",
    "Time": "Minutes (Season)",
    "Goals": "Goals (Season)",
    "xG": "Expected Goals (Season)",
    "Assists": "Assists (Season)",
    "xA": "Expected Assists (Season)",
    "Shots": "Total Shots (Season)",
    "Key Passes": "Key Passes (Season)",
    "Yellow Cards": "Yellow Cards (Season)",
    "Red Cards": "Red Cards (Season)",
    "npg": "Non-Penalty Goals (Season)",
    "npxG": "Non-Penalty Expected Goals (Season)",
    "xGChain": "xG Chain (Season)",
    "xGBuildup": "xG Buildup (Season)"
}

players = players.rename(columns=rename_dict)

# Delete unnecessary columns
players = players.drop(columns=["Team Title", "League", "Value Date"])

# Show first columns
players.head()

,Player ID,Player Name,Nationality,Team Position in League,UEFA league ranking,Position,Birth Date,Height,Foot,Matches (Season),...,Total Shots (Season),Key Passes (Season),Yellow Cards (Season),Red Cards (Season),Non-Penalty Goals (Season),Non-Penalty Expected Goals (Season),xG Chain (Season),xG Buildup (Season),Season,Market Value
0,532,Claudio Pizarro,Peru,18,4,CF,1978-10-03,184.0,right,16,...,16,7,0,0,1,1.863683,2.433829,1.129747,17/18,500000.0
1,532,Claudio Pizarro,Peru,8,4,CF,1978-10-03,184.0,right,26,...,25,10,1,0,5,2.712019,4.449489,1.552150,18/19,500000.0
2,532,Claudio Pizarro,Peru,16,3,CF,1978-10-03,184.0,right,18,...,4,5,0,0,0,0.433545,1.099479,0.333020,19/20,400000.0
3,1565,Alexander Meier,Germany,8,4,SS,1983-01-17,196.0,right,1,...,1,0,0,0,1,0.309795,0.444714,0.134919,17/18,750000.0
5,3306,Jonathan Walters,Ireland,7,2,RW,1983-09-20,183.0,right,3,...,1,0,0,0,0,0.179436,0.179436,0.000000,17/18,2000000.0

In [55]:
print(players.columns)

Index(['Player ID', 'Player Name', 'Nationality', 'Team Position in League',
       'UEFA league ranking', 'Position', 'Birth Date', 'Height', 'Foot',
       'Matches (Season)', 'Minutes (Season)', 'Goals (Season)',
       'Goal Contribution Share', 'Expected Goals (Season)',
       'Assists (Season)', 'Expected Assists (Season)', 'Total Shots (Season)',
       'Key Passes (Season)', 'Yellow Cards (Season)', 'Red Cards (Season)',
       'Non-Penalty Goals (Season)', 'Non-Penalty Expected Goals (Season)',
       'xG Chain (Season)', 'xG Buildup (Season)', 'Season', 'Market Value'],
      dtype='object')